version: "3.9"

services:
  app:
    build: .
    environment:
      DB_NAME:     ${DB_NAME}
      DB_USER:     ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      # ---
      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
    ports:
      - "5000:5000" # Maps host port 5000 to container port 5000
    depends_on:
      - db
  # -------------------------------------------------
  # Lightweight MariaDB (Alpine)
  # -------------------------------------------------
  db:
    image: yobasystems/alpine-mariadb:11.4.8
    container_name: mariadb_alpine
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER:     ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}

    volumes:
      - db_data:/var/lib/mysql        # persistent storage
      - ./inventory.sql:/docker-entrypoint-initdb.d/inventory.sql
    ports:
      - "${DB_EXTERNAL_PORT}:3306"

  # -------------------------------------------------
  # phpMyAdmin
  # -------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST:         ${DB_HOST}  # This should match the service name for MariaDB.
      PMA_USER:         ${DB_USER}
      PMA_PASSWORD:     ${DB_PASSWORD}
      PMA_ABSOLUTE_URI: http://localhost:8080/
    ports:
      - "8080:80"
    # volumes:
      # - /sessions     # optional â€“ store php sessions outside the container

volumes:
  db_data:
