
version: "3.9"

services:
  app:
    build: .
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}

      DB_PORT: ${DB_PORT}
      DB_HOST: ${DB_HOST}
      # #
      # DB_HOST: localhost
      # DB_PORT: 3307
    depends_on:
      - db
  # -------------------------------------------------
  # Lightweight MariaDB (Alpine)
  # -------------------------------------------------
  db:
    image: yobasystems/alpine-mariadb:11.4.8
    container_name: mariadb_alpine
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD:      ${DB_PASSWORD}

      # #
      # MYSQL_DATABASE: inventory_db
      # MYSQL_USER: root
      # MYSQL_ROOT_PASSWORD: secretRootPwd
      # MYSQL_PASSWORD:      secretRootPwd

    volumes:
      - db_data:/var/lib/mysql        # persistent storage
      - ./inventory.sql:/docker-entrypoint-initdb.d/inventory.sql
    ports:
      - "${DB_PORT}:3306"

  # -------------------------------------------------
  # phpMyAdmin
  # -------------------------------------------------
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PMA_HOST: db  # This should match the service name for MariaDB
      PMA_USER: appuser
      PMA_PASSWORD: appUserPwd
      PMA_ABSOLUTE_URI: http://localhost:8080/
    ports:
      - "8080:80"
    # volumes:
      # - /sessions                     # optional â€“ store php sessions outside the container

volumes:
  db_data:
